### ISSUE TITLE
erstmal danke für den Ban

### ISSUE THREAD

**Issue by note3crafter** [PocketGold-MP/PocketGold-MP#1]
weil man es nicht einsehen kann das man eine regel bricht finde sowas echt cool das man nicht mal was einsehen kann!

**Comment by ElektroPrinz** [comment]
Pffff, macht er eine Issue AUF nur um das zuschreiben.

**Comment by IchHackeNetDEV** [comment]
Unnötig

**Comment by note3crafter** [comment]
ich finde es unnötig das ihr Lizensen bricht

**Comment by IchHackeNetDEV** [comment]
Finde diesen ban unnötig

**Comment by note3crafter** [comment]
ich finde euren ban unnötig

**Comment by IchHackeNetDEV** [comment]
Nettes Team btw :kappa:

**Comment by note3crafter** [comment]
Ja euer Team ist beste xD nicht mal einsehen das IHR ein fehler macht und rumheult weil ich es mal emre geschickt habe  dazu muss ich sagen das es lächerlich ist einen dafür zu bannen wieso macht man sowas nicht gleich wieso

**Comment by ElektroPrinz** [comment]
Note, note, note, kannst du nicht einfach das Thema beenden und uns alle inruhe lassen..
